global.BLACK_FILLER = 'BLACK_FILLER';
global.READY_ADS_SIGN_SEPARATOR = '#';
global.READY_ADS_INNER_DATA_SIGN_SEPARATOR = ':';
global.BLOCKED = 'BLOCKED';
global.COUNT = 'COUNT';
global.ERROR = 'ERROR';
global.FILLER = 'FILLER';
global.EMPTY_STRING = '';
global.ALREADY_HANDLING_TEXT = 'Already handling adsReadyCacheKey';
